export default function RulesPage(){
 const sections=[
 ['Participação e divisões','A inscrição é por convite, com validação do WhatsApp e aprovação da organização. Existem três divisões: M1+, M1 e M2. Cada jogador indica se joga à esquerda ou à direita.'],
 ['A ronda da semana','Cada jogador participa em quatro jogos de 20 minutos. A dupla mantém-se fixa durante os quatro jogos e muda de campo entre jogos. Os adversários variam sempre que as combinações e os campos o permitem. Os horários e campos são publicados após o sorteio.'],
 ['Sorteio das duplas','O sorteio é aleatório dentro de cada divisão, juntando um jogador de esquerda e um de direita. Não se repete o parceiro da semana anterior.'],
 ['Pontuação e bónus','Cada vitória vale 3 pontos e cada derrota vale 1 ponto, atribuídos individualmente aos dois jogadores da dupla. A partir da segunda vitória consecutiva, cada vitória acrescenta 1 ponto de bónus. Uma derrota interrompe a sequência. O bónus recomeça em cada semana; os pontos acumulam durante o mês.'],
 ['Subidas e descidas','A cada duas semanas, sobe o melhor pontuado de esquerda e o melhor de direita; descem o pior pontuado de cada lado, entre divisões adjacentes. Quem está em M1+ não sobe mais e quem está em M2 não desce mais. Os jogadores mantêm os pontos acumulados ao mudar de divisão.'],
 ['Campeões do mês','Há três campeões: o jogador com mais pontos de M1+, o de M1 e o de M2, independentemente do lado. Em caso de empate, vence o mais velho. Depois de apurados os campeões, o novo mês começa com os pontos a zero e o histórico fica guardado.'],
 ['Registo de resultados','Um participante regista a vitória ou derrota da sua dupla no link dos jogos. O resultado aplica-se aos quatro jogadores. Depois de confirmado, apenas a organização pode corrigir o resultado.'],
 ['Faltas e substituições','Comunica a ausência no grupo, indicando o dia ou a ronda. Os quatro jogos ficam a aguardar suplente. O administrador pode escolher um jogador aprovado do mesmo lado e divisão, ou aprovar um voluntário que se ofereça no grupo. Até à aprovação, ninguém ocupa a vaga. Os pontos pertencem a quem joga; o ausente recebe zero nessa ronda. Se já houver resultados, a situação é tratada pela organização, sem apagar resultados. Desistências durante os jogos devem ser comunicadas à organização.']
 ];
 return <main className="rules-page"><header><div className="ultimate-logo"><img src="/ultimate-challenge.png" alt="Ultimate Challenge"/></div><span>PREMIER PADEL CLUB</span></header><section className="rules-intro"><p>ULTIMATE CHALLENGE</p><h1>As regras do jogo.</h1><p>Quatro jogos. Uma dupla. Um novo desafio a cada semana.</p></section><div className="rules-content">{sections.map(([title,text],i)=><section key={title}><span className="rules-number">{String(i+1).padStart(2,'0')}</span><div><h2>{title}</h2><p>{text}</p>{i===3&&<table><caption>Exemplos numa semana</caption><thead><tr><th>Resultados</th><th>Pontos</th></tr></thead><tbody>{[['4 vitórias consecutivas','15'],['3 vitórias consecutivas + 1 derrota','12'],['2 vitórias consecutivas + 2 derrotas','9'],['Vitória · derrota · derrota · vitória','8']].map(([r,p])=><tr key={r}><td>{r}</td><td>{p}</td></tr>)}</tbody></table>}</div></section>)}</div><footer><a href="/jogos">Consultar os jogos →</a><p>Ultimate Challenge · Premier Padel Club</p></footer></main>;
}
