import {useEffect,useState} from 'react';
import {Button} from './ui/button';
import {Textarea} from './ui/textarea';
import {api} from './whatsapp-live';
type Data={enabled:boolean;players:{id:string;name:string}[];history:{id:string;action:string}[];error:{at:string;message:string}|null};
export default function AIBotSettings(){
 const [data,setData]=useState<Data|null>(null),[playerId,setPlayer]=useState(''),[text,setText]=useState('Tenho algum jogo hoje?'),[answer,setAnswer]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const refresh=()=>api<Data>('/admin/bot').then(setData);
 useEffect(()=>{void refresh().catch(e=>setError(e.message));},[]);
 return <section className="panel" style={{marginBottom:24}}><div className="section-heading"><div><h2>IA no grupo WhatsApp</h2><p>Perguntas naturais sobre jogos, pontos, classificação e regras, sem comandos.</p></div>{data&&<Button disabled={busy} onClick={async()=>{setBusy(true);try{await api('/admin/bot','PUT',{enabled:!data.enabled});await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>{data.enabled?'Desativar IA':'Ativar IA'}</Button>}</div><p>{data?.enabled?'IA ativada.':'IA desativada.'} Usa a chave OpenAI guardada acima. Limites: 4 perguntas por jogador/minuto e 60 interpretações/hora na plataforma. Conversas irrelevantes também podem consumir uma interpretação.</p><p>Responde apenas a jogadores aprovados no grupo associado; ignora as mensagens enviadas pelo próprio número do bot. As respostas são apenas de consulta. Os resultados e substituições mantêm os fluxos de aprovação existentes.</p>{data?.error&&<p className="form-error">Última falha ({data.error.at}): {data.error.message}</p>}{error&&<p className="form-error" role="alert">{error}</p>}
 <form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');setAnswer('');try{const r=await api<{answer:string|null}>('/admin/bot/simulate','POST',{playerId,text});setAnswer(r.answer??'O bot ficaria em silêncio nesta mensagem.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><label className="field">Simular como jogador<select required value={playerId} onChange={e=>setPlayer(e.target.value)} style={{padding:12,border:'1px solid #d9e3e9',borderRadius:8}}><option value="">Selecionar jogador</option>{data?.players.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="field">Pergunta<Textarea required maxLength={1500} value={text} onChange={e=>setText(e.target.value)}/></label><p>O simulador consulta a OpenAI e usa os dados reais, mas não envia mensagens ao WhatsApp.</p><Button disabled={busy||!playerId} type="submit">{busy?'A interpretar…':'Testar pergunta'}</Button></form>{answer&&<div className="invite-preview" role="status">{answer}</div>}<h3 style={{marginTop:24}}>Últimas respostas preparadas</h3><Button variant="outline" onClick={()=>refresh().catch(e=>setError(e.message))}>Atualizar histórico</Button>{data?.history.map(h=><p key={h.id} style={{whiteSpace:'pre-wrap',borderBottom:'1px solid #e3e9ed',padding:'12px 0'}}>{h.action}</p>)}
 </section>;
}
