import {useEffect,useState} from 'react';
import {api} from './whatsapp-live';
import {Button} from './ui/button';
import {Input} from './ui/input';
export default function CalendarSettings(){
 const [data,setData]=useState<{weekday:number|null;time:string}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[note,setNote]=useState('');
 useEffect(()=>{api<{weekday:number|null;time:string}>('/admin/calendar').then(setData).catch(e=>setError(e.message));},[]);
 return <section className="panel"><h2>Calendário semanal</h2><p>Define o dia habitual e a hora de início dos jogos, na hora de Angola. Aplica-se às próximas rondas; os jogos já criados mantêm o horário.</p>{data&&<form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');setNote('');try{const saved=await api<{weekday:number;time:string}>('/admin/calendar','PUT',data);setData(saved);setNote('Calendário guardado.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><fieldset className="calendar-days" disabled={busy}><legend>Em que dia da semana se joga?</legend><p>Seleciona o dia habitual dos jogos.</p><div className="calendar-day-options">{[[1,'Segunda'],[2,'Terça'],[3,'Quarta'],[4,'Quinta'],[5,'Sexta'],[6,'Sábado'],[0,'Domingo']].map(([value,label])=><label key={value} className={`calendar-day ${data.weekday===value?'is-selected':''}`}><input type="radio" name="weekday" value={value} checked={data.weekday===value} onChange={()=>{setData({...data,weekday:Number(value)});setNote('');}}/><span>{label}</span><span aria-hidden="true" className="calendar-day-mark">{data.weekday===value?'✓':'○'}</span></label>)}</div><p className="calendar-day-summary" role="status">{data.weekday===null?'Ainda não selecionaste um dia.':`Dia escolhido: ${['Domingo','Segunda-feira','Terça-feira','Quarta-feira','Quinta-feira','Sexta-feira','Sábado'][data.weekday]}`}</p></fieldset><label className="field">Hora de início<Input type="time" required disabled={busy} value={data.time} onChange={e=>setData({...data,time:e.target.value})}/></label><p>Quatro jogos de 20 minutos por dupla. Podes ajustar a data e a hora antes de sortear cada ronda.</p><Button type="submit" disabled={busy||data.weekday===null}>{busy?'A guardar…':'Guardar calendário'}</Button></form>}{error&&<p className="form-error" role="alert">{error}</p>}{note&&<p role="status">{note}</p>}</section>;
}
