import { useEffect, useState } from 'react';
import { api } from './whatsapp-live';
import { Trophy, ArrowRight, CalendarDays } from 'lucide-react';
type CompetitionData = { anchor:string|null; status:{blocked:string|null;nextMovement:string;checkedAt:string}|null; months:{month:string;champions:{division:string;player:{name:string;points:number}|null}[];table:{id:string;name:string;division:string;points:number;wins:number;losses:number}[]}[]; movements:{date:string;changes:{id:string;name:string;from:string;to:string;points:number}[]}[] };
export default function CompetitionLive({history=false}:{history?:boolean}) {
 const [data,setData]=useState<CompetitionData|null>(null);const [error,setError]=useState('');
 useEffect(()=>{let active=true;const refresh=()=>api<CompetitionData>('/admin/competition').then(d=>{if(active){setData(d);setError('');}}).catch(e=>{if(active)setError(e.message);});void refresh();const t=setInterval(refresh,30000);return()=>{active=false;clearInterval(t);};},[]);
 return <div className="competition-live">{error&&<p className="form-error" role="alert">{error}</p>}{!data&&!error&&<p>A carregar o calendário…</p>}{data&&<>
 <section className="panel"><div className="section-heading"><div><h2>Calendário automático</h2><p>Verificado a cada minuto · hora de Luanda</p></div><CalendarDays size={22}/></div><div className="rules-grid"><div><span>Primeiro ciclo</span><strong>{data.anchor??'Começa no primeiro jogo publicado'}</strong></div><div><span>Próxima troca</span><strong>{data.status?.nextMovement??'14 dias após o primeiro jogo'}</strong></div><div><span>Pontos nas trocas</span><strong>Mantêm-se durante o mês</strong></div><div><span>Fecho mensal</span><strong>Automático na mudança do mês</strong></div></div>{data.status?.blocked&&<p className="info-note" role="status">{data.status.blocked}</p>}<p className="competition-note">Sobem o melhor esquerda e o melhor direita. Descem o pior esquerda e o pior direita. M1+ não sobe; M2 não desce. No empate, o mais velho fica melhor classificado.</p></section>
 {history&&<><section className="panel"><h2>Campeões mensais</h2>{!data.months.length?<p className="competition-note">Ainda não há meses encerrados. Os vencedores e a classificação final serão guardados aqui.</p>:data.months.map(m=><div className="competition-month" key={m.month}><h3>{m.month}</h3><div className="competition-champions">{m.champions.map(c=><div key={c.division}><Trophy size={20}/><span>{c.division}</span><strong>{c.player?.name??'Sem jogos concluídos'}</strong><small>{c.player?`${c.player.points} pontos`:'Sem campeão atribuído'}</small></div>)}</div><details><summary>Ver classificação final</summary><div className="table-scroll"><table><thead><tr><th>Jogador</th><th>Divisão</th><th>Pontos</th><th>Vitórias</th><th>Derrotas</th></tr></thead><tbody>{m.table.map(p=><tr key={p.id}><td>{p.name}</td><td>{p.division}</td><td>{p.points}</td><td>{p.wins}</td><td>{p.losses}</td></tr>)}</tbody></table></div></details></div>)}</section><section className="panel"><h2>Subidas e descidas</h2>{!data.movements.length?<p className="competition-note">As trocas efetuadas aparecem aqui, com os pontos que cada jogador manteve.</p>:data.movements.map(m=><div className="competition-month" key={m.date}><h3>{m.date}</h3>{m.changes.map(c=><div className="competition-change" key={c.id}><strong>{c.name}</strong><span>{c.from} <ArrowRight size={13}/> {c.to}</span><small>{c.points} pontos mantidos</small></div>)}</div>)}</section></>}
 </>}</div>;
}
