import {useEffect,useState} from 'react';
import {api} from './whatsapp-live';
import {Button} from './ui/button';
type Player={id:string;name:string;side:string;division:string};
type Vacancy={id:string;round:number;date:string;playerId:string;name:string;side:string;division:string;candidates:string[];status:string;substituteId?:string};
type Data={players:Player[];vacancies:Vacancy[];games:{round:number;date:string;a:string[];b:string[]}[]};
export default function Substitutions(){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[round,setRound]=useState(''),[absent,setAbsent]=useState(''),[selection,setSelection]=useState<Record<string,string>>({});
 async function refresh(){setData(await api<Data>('/admin/substitutions'));}
 useEffect(()=>{let active=true;const poll=()=>api<Data>('/admin/substitutions').then(d=>{if(active)setData(d);}).catch(e=>{if(active)setError(e.message);});void poll();const timer=setInterval(poll,10000);return()=>{active=false;clearInterval(timer);};},[]);
 async function act(path:string,body:unknown){setBusy(true);setError('');try{await api('/admin/substitutions'+path,'POST',body);await refresh();setNotice('Alteração guardada. Atualiza a página para carregar os jogos e a classificação atualizados.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="panel substitutions-panel"><div className="section-heading"><div><h2>Ausências e suplentes</h2><p>A escolha é sempre tua: seleciona um jogador ou aprova um voluntário do WhatsApp.</p></div><Button variant="outline" disabled={busy} onClick={()=>refresh().catch(e=>setError(e.message))}>Atualizar lista</Button></div><p>Guarda primeiro outras alterações ao torneio. Estas ações ficam guardadas imediatamente.</p>
 {error&&<p className="form-error" role="alert">{error}</p>}{notice&&<p role="status">{notice} <Button variant="outline" onClick={()=>location.reload()}>Atualizar página</Button></p>}
 {data&&<><form className="substitution-form" onSubmit={e=>{e.preventDefault();void act('',{round:Number(round),playerId:absent});}}><label className="field">Ronda<select required value={round} onChange={e=>{setRound(e.target.value);setAbsent('');}}><option value="">Escolher ronda</option>{[...new Set(data.games.map(g=>g.round))].map(r=><option key={r} value={r}>Ronda {r} · {data.games.find(g=>g.round===r)?.date}</option>)}</select></label><label className="field">Jogador ausente<select required value={absent} onChange={e=>setAbsent(e.target.value)}><option value="">Escolher jogador</option>{data.players.filter(p=>data.games.some(g=>g.round===Number(round)&&[...g.a,...g.b].includes(p.id))).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><Button disabled={busy||!absent} type="submit">Registar ausência</Button></form>
 {!data.vacancies.some(v=>v.status==='pending')&&<p>Não há vagas à espera de suplente.</p>}
 {data.vacancies.filter(v=>v.status==='pending').map(v=>{const eligible=data.players.filter(p=>p.id!==v.playerId&&p.division===v.division&&p.side===v.side&&!data.games.some(g=>(g.round===v.round||g.date===v.date)&&[...g.a,...g.b].includes(p.id)));return <div className="substitution-vacancy" key={v.id}><h3>{v.name} · Aguarda suplente</h3><p>Ronda {v.round} · {v.date} · {v.division} · {v.side} · 4 jogos</p><p>Voluntários: {v.candidates.length?v.candidates.map(id=>data.players.find(p=>p.id===id)?.name??'Jogador').join(', '):'Ainda não há candidatos.'}</p><label className="field">Escolher suplente<select value={selection[v.id]??''} onChange={e=>setSelection({...selection,[v.id]:e.target.value})}><option value="">Selecionar jogador aprovado</option>{eligible.map(p=><option key={p.id} value={p.id}>{p.name}{v.candidates.includes(p.id)?' · Voluntário':''}</option>)}</select></label>{!eligible.length&&<p>Não há jogadores livres do mesmo lado e divisão. Aprova a inscrição de um suplente para o poderes selecionar.</p>}<div className="dialog-actions"><Button variant="outline" disabled={busy} onClick={()=>act('/'+v.id+'/cancel',{})}>Cancelar ausência</Button><Button disabled={busy||!selection[v.id]} onClick={()=>act('/'+v.id+'/approve',{playerId:selection[v.id]})}>Aprovar substituição</Button></div></div>;})}
 <p>Os pontos pertencem ao suplente que joga. O ausente não recebe pontos desta ronda.</p></>}
 </section>;
}
